import {StyleSheet} from 'react-native';

const PuzzleLetterStyle = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    width: 24,
    height: 32,
    borderRadius: 5,
    margin: 1,
    borderWidth: 1,
    borderColor: '#D6D9D9',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 10,
  },
  activeContainer: {
    backgroundColor: '#E8A546',
    width: 23,
    height: 31,
    borderRadius: 5,
    margin: 1,
    alignItems: 'center',
  },
  image: {
    width: 12,
    height: 18,
    resizeMode: 'contain',
    color: 'black',
    marginTop: 8,
  },
  cardNumber: {
    width: 15,
    height: 16,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#D6D9D9',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
    backgroundColor: 'white',
  },
  activeCardNumber: {
    width: 15,
    height: 16,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#D6D9D9',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    position: 'relative',
    bottom: 4,
    zIndex: 2,
  },
  number: {
    color: '#1D3A62',
    fontWeight: '900',
    fontSize: 10,
  },
  textInput: {
    backgroundColor: '#E8A546',
    color: '#1D3A62',
    fontWeight: '600',
    zIndex: 1,
    position: 'relative',
    fontSize: 18,
    paddingBottom: 1,
    borderBottomWidth: 0,
    textDecorationLine: 'none',
    textTransform: 'uppercase',
    textAlignVertical: 'top',
    borderRadius: 5,
  },
});

export default PuzzleLetterStyle;
